### ISSUE TITLE
Breaks piazza.com

### ISSUE THREAD

**Issue by ashaheedq** [mattcdowning/nomailto#6]
Hi, when this extension enabled the website Piazza.com breaks. I can't click on any hypertext and cannot scroll.

**Comment by mattcdowning** [comment]
@ashaheedq Are there errors in the console? What OS and version of Chrome are you using? I'm using Version 72.0.3626.17 on macOS and Piazza.com is working fine for me. Although to be clear, I am not "logged in" on Piazza...just viewing their marketing site.

**Comment by ashaheedq** [comment]
To be specific the issue is that I cannot scroll down to see comments when a post is selected and I cannot copy texts too. However, everything works fine when the extension is disabled.
attached screenshot of the console.
<img width="554" alt="screen shot 2018-12-20 at 6 47 14 pm" src="https://user-images.githubusercontent.com/22966206/50317141-1079ec80-0488-11e9-80b4-4e87848a7f59.png">

**Comment by ashaheedq** [comment]
Sorry, I forgot to mention that I am using Mac OS Mojave and chrome version 71.0.3578.98.

**Comment by mattcdowning** [comment]
Those are just warnings so I don't think the Element.createShadowRoot deprecation is the issue. I do not have access to the Piazza platform so I don't have any "Posts" to select and thus have no way of testing your issue. Wish I could be of more help. Please feel free to make a PR if you find a resolution!
